[book]
authors = ["ShiJiCheng, ZhangHanDong"]
language = "en"
multilingual = false
src = "src"
title = "Rust you don't know"

[build]
create-missing = true

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
max-level = 2

[output.html.fold]
enable = true
level = 0